# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='mobile',
            field=models.IntegerField(null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 18, 28, 58, 780702), verbose_name='登录验证时间'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 18, 28, 58, 781347), verbose_name='loginTime'),
        ),
    ]
