# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 07:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoregood', models.IntegerField(default='0', verbose_name='好评数')),
                ('scoremiddle', models.IntegerField(default='0', verbose_name='中评数')),
                ('scorepoor', models.IntegerField(default='0', verbose_name='差评数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '买家好评',
                'verbose_name_plural': '买家好评',
            },
        ),
        migrations.CreateModel(
            name='idGuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPcGuid', models.CharField(max_length=30, verbose_name='账号pcGuid')),
                ('userMobileGuid', models.CharField(max_length=30, verbose_name='账号手机Guid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'guid',
                'verbose_name_plural': 'guid',
            },
        ),
        migrations.CreateModel(
            name='jdUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdUsername', models.CharField(max_length=30, verbose_name='京东账号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '京东账号',
                'verbose_name_plural': '京东账号',
            },
        ),
        migrations.CreateModel(
            name='sellscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoregood', models.IntegerField(default='0', verbose_name='好评数')),
                ('scoremiddle', models.IntegerField(default='0', verbose_name='中评数')),
                ('scorepoor', models.IntegerField(default='0', verbose_name='差评数')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '卖家好评',
                'verbose_name_plural': '卖家好评',
            },
        ),
        migrations.CreateModel(
            name='tbUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbUsername', models.CharField(max_length=30, verbose_name='淘宝账号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '淘宝账号',
                'verbose_name_plural': '淘宝账号',
            },
        ),
    ]
