# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 20:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170529_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcguid',
            name='PcGuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='pcGuid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='addtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 29, 20, 42, 46, 205438), null=True, verbose_name='登录验证时间'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='biosid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='biosid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='boardid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='boardid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='cpuid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='cpuid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='diskid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='diskid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='resip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='RegisterIP'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 20, 42, 46, 206029), verbose_name='loginTime'),
        ),
    ]
