# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170529_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcguid',
            name='PcGuid',
            field=models.IntegerField(blank=True, max_length=60, null=True, verbose_name='pcGuid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='addtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 5, 29, 21, 8, 50, 276821), null=True, verbose_name='登录验证时间'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 29, 21, 8, 50, 277417), verbose_name='loginTime'),
        ),
    ]
