# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 17:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170529_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcguid',
            name='addtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 9, 17, 29, 40, 90224), null=True, verbose_name='登录验证时间'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 9, 17, 29, 40, 90834), verbose_name='loginTime'),
        ),
    ]
