# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 11:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170618_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visuallog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resip', models.GenericIPAddressField(verbose_name='IP')),
                ('addtime', models.DateTimeField(default=datetime.datetime(2017, 6, 19, 11, 8, 41, 241413), verbose_name='loginTime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'guidlog',
                'verbose_name_plural': 'guidlog',
            },
        ),
        migrations.AddField(
            model_name='pcguidlog',
            name='visual',
            field=models.IntegerField(blank=True, default=0, max_length=10, null=True, verbose_name='pcGuid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='addtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 6, 19, 11, 8, 41, 239938), null=True, verbose_name='登录验证时间'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='PcGuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.pcGuid', verbose_name='pcGuid'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='addtime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 11, 8, 41, 240642), verbose_name='loginTime'),
        ),
    ]
