# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20170619_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcguid',
            name='PcGuid',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='pcGuid'),
        ),
        migrations.AlterField(
            model_name='pcguid',
            name='addtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='登录验证时间'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='addtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='loginTime'),
        ),
        migrations.AlterField(
            model_name='pcguidlog',
            name='visual',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='pcGuid'),
        ),
        migrations.AlterField(
            model_name='visuallog',
            name='addtime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='loginTime'),
        ),
    ]
