# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-02 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20170625_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='phoneid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneid', models.CharField(max_length=120, null=True, unique=True, verbose_name='pcGuid')),
                ('cpuid', models.CharField(blank=True, max_length=60, null=True, verbose_name='cpuid')),
                ('resip', models.GenericIPAddressField(blank=True, null=True, verbose_name='RegisterIP')),
                ('addtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='登录验证时间')),
                ('is_blacklist', models.IntegerField(blank=True, default=0, null=True, verbose_name='blacklist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'phoneid',
                'verbose_name_plural': 'phoneid',
            },
        ),
        migrations.CreateModel(
            name='phonelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resip', models.GenericIPAddressField(verbose_name='IP')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='loginTime')),
                ('phoneid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.phoneid', verbose_name='phoneid')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'phonelog',
                'verbose_name_plural': 'phonelog',
            },
        ),
        migrations.CreateModel(
            name='realName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resip', models.GenericIPAddressField(verbose_name='IP')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='loginTime')),
                ('realnameid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.phoneid', unique=True, verbose_name='phoneid')),
            ],
            options={
                'verbose_name': 'realName',
                'verbose_name_plural': 'realName',
            },
        ),
    ]
