# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_phoneid_phonelog_realname'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobileid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileid', models.CharField(max_length=120, null=True, unique=True, verbose_name='mobileid')),
                ('resip', models.GenericIPAddressField(blank=True, null=True, verbose_name='RegisterIP')),
                ('addtime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='登录验证时间')),
                ('is_blacklist', models.IntegerField(blank=True, default=0, null=True, verbose_name='blacklist')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.CreateModel(
            name='real_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realNameid', models.CharField(max_length=30, unique=True, verbose_name='RealNameid')),
                ('resip', models.GenericIPAddressField(verbose_name='IP')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='loginTime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related_name')),
            ],
            options={
                'verbose_name': 'realName',
                'verbose_name_plural': 'realName',
            },
        ),
        migrations.RenameModel(
            old_name='phonelog',
            new_name='mobilelog',
        ),
        migrations.RemoveField(
            model_name='phoneid',
            name='user',
        ),
        migrations.RemoveField(
            model_name='realname',
            name='realnameid',
        ),
        migrations.AlterField(
            model_name='mobilelog',
            name='phoneid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mobileid', verbose_name='phoneid'),
        ),
        migrations.DeleteModel(
            name='phoneid',
        ),
        migrations.DeleteModel(
            name='realName',
        ),
    ]
