# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-03 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170703_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklistlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='addTime')),
                ('resip', models.GenericIPAddressField(null=True, verbose_name='IP')),
                ('Remarks', models.CharField(max_length=9999, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related_name')),
            ],
        ),
        migrations.RenameField(
            model_name='mobilelog',
            old_name='phoneid',
            new_name='mobileid',
        ),
    ]
