# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170703_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilelog',
            name='mobileid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.mobileid', verbose_name='mobileid'),
        ),
    ]
