# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 00:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170706_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='alipay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alipay', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='alipay')),
                ('is_blacklist', models.IntegerField(blank=True, default=0, null=True, verbose_name='blacklist')),
            ],
            options={
                'verbose_name': 'alipay',
                'verbose_name_plural': 'alipay',
            },
        ),
        migrations.CreateModel(
            name='Bankcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bankcard', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Bankcard')),
                ('is_blacklist', models.IntegerField(blank=True, default=0, null=True, verbose_name='blacklist')),
            ],
            options={
                'verbose_name': 'Bankcard',
                'verbose_name_plural': 'Bankcard',
            },
        ),
        migrations.CreateModel(
            name='Idcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idcard', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Idcard')),
                ('is_blacklist', models.IntegerField(blank=True, default=0, null=True, verbose_name='blacklist')),
            ],
            options={
                'verbose_name': 'Idcard',
                'verbose_name_plural': 'Idcard',
            },
        ),
        migrations.CreateModel(
            name='wechat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='wechat')),
                ('is_blacklist', models.IntegerField(blank=True, default=0, null=True, verbose_name='blacklist')),
            ],
            options={
                'verbose_name': 'wechat',
                'verbose_name_plural': 'wechat',
            },
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='alipay',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='bankID',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='bankName',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='qq',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='wechat',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='wechatName',
        ),
        migrations.AddField(
            model_name='wechat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='idcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='bankcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='alipay',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
