# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-05 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.IntegerField()),
            ],
            options={
                'verbose_name': 'advert',
                'verbose_name_plural': 'advert',
            },
        ),
    ]
