# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mobileid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformVersion', models.CharField(max_length=200, null=True)),
                ('andriodname', models.CharField(max_length=500, null=True)),
                ('label_User_portrait', models.CharField(max_length=500, null=True)),
                ('mobileSort', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.CreateModel(
            name='mobiletask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileSort', models.IntegerField(choices=[(1, 'add_User'), (2, 'ADD_GROUP'), (3, 'send_message_to_user_Accoutid'), (4, 'send_message_to_GROUP_Accoutid'), (5, 'send_message_to_friend_list'), (6, 'send_message_to_GROUP_list')], null=True)),
                ('AccountId', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('statusTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Done'), (1, 'Start_Task'), (2, 'working')], default=1, null=True)),
                ('mobileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.CreateModel(
            name='mobiletasklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto1.mobileid')),
                ('mobiletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto1.mobiletask')),
            ],
        ),
        migrations.CreateModel(
            name='softid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appPackage', models.CharField(max_length=200, null=True)),
                ('appActivity', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.AddField(
            model_name='mobiletask',
            name='softid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto1.softid'),
        ),
    ]
