# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 23:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto1', '0010_auto_20170720_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletasklog',
            name='logdatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 31, 23, 16, 22, 911019)),
        ),
    ]
