# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto1', '0011_auto_20170731_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserPortrait', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortraitlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains', models.CharField(max_length=9999)),
                ('UserPortSort', models.IntegerField(choices=[(1, 'QQSendMessage'), (2, 'QQSaysay'), (3, 'QQSpace')])),
                ('startTime', models.DateTimeField()),
                ('UserPortkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto1.UserPortrait')),
            ],
        ),
        migrations.AlterField(
            model_name='mobiletasklog',
            name='logdatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 20, 47, 0, 82212)),
        ),
    ]
