# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto1', '0012_auto_20170818_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiletasklog',
            name='mobileid',
        ),
        migrations.RemoveField(
            model_name='mobiletasklog',
            name='mobiletask',
        ),
        migrations.DeleteModel(
            name='mobiletasklog',
        ),
    ]
