# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto1', '0013_auto_20170818_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobiletasklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=30, null=True)),
                ('logid', models.CharField(max_length=15, null=True)),
                ('logdatetime', models.DateTimeField(default=datetime.datetime(2017, 8, 18, 21, 0, 7, 936537))),
                ('mobileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto1.mobileid')),
                ('mobiletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto1.mobiletask')),
            ],
            options={
                'verbose_name': 'mobiletasklog',
                'verbose_name_plural': 'mobiletasklog',
            },
        ),
    ]
