# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 21:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto1', '0014_mobiletasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletasklog',
            name='logdatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 18, 21, 1, 1, 607814)),
        ),
    ]
