# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 17:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cryapp', '0005_auto_20170619_1728'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deposit',
                'verbose_name_plural': 'deposit',
            },
        ),
        migrations.CreateModel(
            name='orderBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='总金额(元)')),
                ('orderBillSort', models.IntegerField(blank=True, choices=[(0, 'refund'), (1, 'CryOrders'), (2, 'FlowOrder')], null=True, verbose_name='订单状态')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('CryOrderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderBillCryOrderid', to='cryapp.CryOrder')),
            ],
            options={
                'verbose_name': 'orderBill',
                'verbose_name_plural': 'orderBill',
            },
        ),
        migrations.CreateModel(
            name='TopUpwithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopUp_withdrawalSort', models.CharField(choices=[(1, 'Top-up'), (2, 'withdrawal')], max_length=20, null=True, verbose_name='交易类型')),
                ('certificate', models.CharField(blank=True, max_length=200, null=True, verbose_name='充值凭证')),
                ('certificateid', models.IntegerField(blank=True, null=True, verbose_name='账单编号')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='金额')),
                ('transfer_account', models.CharField(blank=True, max_length=200, null=True, verbose_name='收款账户')),
                ('status', models.IntegerField(choices=[(1, 'waitting'), (2, 'through'), (3, 'Not_Through')], null=True, verbose_name='审核状态')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='审核时间')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manageUser', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TopUp_withdrawal',
                'verbose_name_plural': 'TopUp_withdrawal',
            },
        ),
    ]
