# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(max_length=50, verbose_name='余额')),
                ('WithDrawAmount', models.FloatField(default=0, verbose_name='提现资金')),
                ('OrdersAmount', models.FloatField(max_length=50, verbose_name='任务资金')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '财务',
                'verbose_name_plural': '财务',
            },
        ),
        migrations.CreateModel(
            name='WithDrawAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WithDrawAmount', models.FloatField(max_length=50, verbose_name='提现资金')),
                ('Status', models.IntegerField(verbose_name='状态1.失败,2成功')),
                ('Error', models.CharField(max_length=22, verbose_name='错误')),
                ('Time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '提现',
                'verbose_name_plural': '提现',
            },
        ),
    ]
