# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 00:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0003_alipaydetail_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaydetail',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alipaydetail',
            name='alipayusername',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alipaydetail',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 0, 53, 38, 92594)),
        ),
    ]
