# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-21 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_auto_20170621_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaydetail',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 16, 31, 48, 974419)),
        ),
        migrations.AlterField(
            model_name='topupwithdrawal',
            name='certificateid',
            field=models.IntegerField(blank=True, max_length=200, null=True, verbose_name='账单编号'),
        ),
    ]
