# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 07:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_auto_20170621_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaydetail',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 22, 7, 52, 19, 957805)),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总金额(元)'),
        ),
        migrations.AlterField(
            model_name='topupwithdrawal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='金额'),
        ),
    ]
