# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-25 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_auto_20170622_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaydetail',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 25, 12, 31, 51, 827112)),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='orderBillSort',
            field=models.IntegerField(blank=True, choices=[(0, 'refund'), (1, 'CryOrders'), (2, 'cost')], null=True, verbose_name='订单状态'),
        ),
    ]
