# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 00:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_auto_20170625_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaydetail',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 29, 0, 11, 32, 820760)),
        ),
    ]
