# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_auto_20170629_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaydetail',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='BankSort',
            field=models.IntegerField(choices=[(1, 'alipay'), (2, 'wechat'), (3, 'jiaotongBank'), (4, 'GongshangBank')], verbose_name='BankSort'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='Status',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on')], default=1, verbose_name='bankStatus'),
        ),
        migrations.AlterField(
            model_name='orderbill',
            name='orderBillSort',
            field=models.IntegerField(blank=True, choices=[(0, 'refund'), (1, 'CryOrders'), (2, 'cost'), (3, 'manageorders')], null=True, verbose_name='订单状态'),
        ),
    ]
