# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-18 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mobileAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQ', models.CharField(max_length=100, null=True)),
                ('QQps', models.CharField(max_length=100, null=True)),
                ('QQmobile', models.CharField(max_length=20, null=True)),
                ('wechat', models.CharField(max_length=100, null=True)),
                ('wechatps', models.CharField(max_length=100, null=True)),
                ('wechatmobile', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'mobileAccount',
                'verbose_name_plural': 'mobileAccount',
            },
        ),
        migrations.CreateModel(
            name='mobileid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformVersion', models.CharField(max_length=200, null=True)),
                ('deviceName', models.CharField(max_length=500, null=True)),
                ('udid', models.CharField(max_length=500, null=True)),
                ('StyleLabel', models.CharField(max_length=500, null=True)),
                ('webserverurl', models.CharField(max_length=500, null=True)),
                ('mobileSort', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.CreateModel(
            name='mobiletask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskSort', models.IntegerField(choices=[(1, 'add_User'), (2, 'ADD_GROUP'), (3, 'send_message_to_friend_list'), (4, 'send_message_to_GROUP_list'), (5, 'send_message_to_user_Accoutid'), (6, 'send_message_to_GROUP_Accoutid'), (7, 'Get_Pople_list'), (8, 'Get_Group_list'), (9, 'Get_Group_People_list')], null=True)),
                ('AccountId', models.CharField(max_length=200, null=True)),
                ('content', models.CharField(max_length=200, null=True)),
                ('startTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('endTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('statusTime', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Done'), (1, 'Start_Task'), (2, 'working')], default=1, null=True)),
                ('mobileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto2.mobileid')),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.CreateModel(
            name='mobiletasklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logname', models.CharField(max_length=30, null=True)),
                ('logid', models.CharField(max_length=15, null=True)),
                ('logdatetime', models.DateTimeField(default=datetime.datetime(2017, 8, 18, 22, 40, 45, 14865))),
                ('mobileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto2.mobileid')),
                ('mobiletask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto2.mobiletask')),
            ],
            options={
                'verbose_name': 'mobiletasklog',
                'verbose_name_plural': 'mobiletasklog',
            },
        ),
        migrations.CreateModel(
            name='softid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appPackage', models.CharField(max_length=200, null=True)),
                ('appActivity', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'mobileid',
                'verbose_name_plural': 'mobileid',
            },
        ),
        migrations.CreateModel(
            name='UserPortrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserPortrait', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserPortraitlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains', models.CharField(max_length=9999)),
                ('UserPortSort', models.IntegerField(choices=[(1, 'QQSendMessage'), (2, 'QQSaysay'), (3, 'QQSpace')])),
                ('startTime', models.DateTimeField()),
                ('UserPortkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto2.UserPortrait')),
            ],
        ),
        migrations.AddField(
            model_name='mobiletask',
            name='softid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto2.softid'),
        ),
        migrations.AddField(
            model_name='mobileaccount',
            name='mobileid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto2.mobileid'),
        ),
    ]
