# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_description', models.CharField(max_length=120)),
                ('link_url', models.CharField(max_length=200)),
            ],
        ),
    ]
