# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 08:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JDGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdid', models.CharField(max_length=50, verbose_name='京东商品ID')),
                ('SendAddress', models.CharField(max_length=50, verbose_name='发货地')),
                ('jdimage', models.ImageField(default='image/default.png', null=True, upload_to='image/jdgoods/%Y/%m')),
                ('jdimage2', models.ImageField(default='image/default.png', null=True, upload_to='image/jdgoods/%Y/%m')),
                ('jdimage3', models.ImageField(default='image/default.png', null=True, upload_to='image/jdgoods/%Y/%m')),
                ('jdKeyword1', models.CharField(max_length=50, verbose_name='1关键词')),
                ('jdPrice1', models.FloatField(max_length=50, verbose_name='1价格')),
                ('jdRemark1', models.CharField(max_length=50, verbose_name='1备注')),
                ('jdKeyword2', models.CharField(max_length=50, verbose_name='1关键词')),
                ('jdPrice2', models.FloatField(max_length=50, verbose_name='2价格')),
                ('jdRemark2', models.CharField(max_length=50, verbose_name='2备注')),
                ('jdKeyword3', models.CharField(max_length=50, verbose_name='3关键词')),
                ('jdPrice3', models.FloatField(max_length=50, verbose_name='3价格')),
                ('jdRemark3', models.CharField(max_length=50, verbose_name='3备注')),
                ('jdKeyword4', models.CharField(max_length=50, verbose_name='4关键词')),
                ('jdPrice4', models.FloatField(max_length=50, verbose_name='4价格')),
                ('jdRemark4', models.CharField(max_length=50, verbose_name='4备注')),
                ('jdKeyword5', models.CharField(max_length=50, verbose_name='5关键词')),
                ('jdPrice5', models.FloatField(max_length=50, verbose_name='5价格')),
                ('jdRemark5', models.CharField(max_length=50, verbose_name='5备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '京东商品ID',
                'verbose_name_plural': '京东商品ID',
            },
        ),
        migrations.CreateModel(
            name='jdshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jdshopname', models.CharField(max_length=50, verbose_name='京东店铺名')),
                ('Remark', models.CharField(max_length=20, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '京东店铺名',
                'verbose_name_plural': '京东店铺名',
            },
        ),
        migrations.CreateModel(
            name='TaobaoGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbID', models.CharField(max_length=50, verbose_name='淘宝商品ID')),
                ('SendAddress', models.CharField(max_length=50, verbose_name='发货地')),
                ('tbimage', models.ImageField(default='image/default.png', null=True, upload_to='image/tbgoods/%Y/%m')),
                ('tbimage2', models.ImageField(default='image/default.png', null=True, upload_to='image/tbgoods/%Y/%m')),
                ('tbimage3', models.ImageField(default='image/default.png', null=True, upload_to='image/tbgoods/%Y/%m')),
                ('tbKeyword1', models.CharField(max_length=50, null=True, verbose_name='1关键词')),
                ('tbPrice1', models.FloatField(max_length=50, null=True, verbose_name='1价格')),
                ('tbRemark1', models.CharField(max_length=50, null=True, verbose_name='1备注')),
                ('tbKeyword2', models.CharField(max_length=50, null=True, verbose_name='1关键词')),
                ('tbPrice2', models.FloatField(max_length=50, null=True, verbose_name='2价格')),
                ('tbRemark2', models.CharField(max_length=50, null=True, verbose_name='2备注')),
                ('tbKeyword3', models.CharField(max_length=50, null=True, verbose_name='3关键词')),
                ('tbPrice3', models.FloatField(max_length=50, null=True, verbose_name='3价格')),
                ('tbRemark3', models.CharField(max_length=50, null=True, verbose_name='3备注')),
                ('tbKeyword4', models.CharField(max_length=50, null=True, verbose_name='4关键词')),
                ('tbPrice4', models.FloatField(max_length=50, null=True, verbose_name='4价格')),
                ('tbRemark4', models.CharField(max_length=50, null=True, verbose_name='4备注')),
                ('tbKeyword5', models.CharField(max_length=50, null=True, verbose_name='5关键词')),
                ('tbPrice5', models.FloatField(max_length=50, null=True, verbose_name='5价格')),
                ('tbRemark5', models.CharField(max_length=50, null=True, verbose_name='5备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '淘宝商品ID',
                'verbose_name_plural': '淘宝商品ID',
            },
        ),
        migrations.CreateModel(
            name='taobaoshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbShopName', models.CharField(max_length=50, verbose_name='淘宝店铺名')),
                ('Remark', models.CharField(max_length=20, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '淘宝店铺名',
                'verbose_name_plural': '淘宝店铺名',
            },
        ),
        migrations.AddField(
            model_name='taobaogoods',
            name='taobaoshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.taobaoshop', verbose_name='所属店铺'),
        ),
        migrations.AddField(
            model_name='taobaogoods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='jdgoods',
            name='jdshopid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.jdshop', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='jdgoods',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
