# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170518_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='platform',
            field=models.CharField(choices=[('taobao', 'taobao'), ('jd', 'jd'), ('tmall', 'tmall'), ('1688', '1688')], default=1, max_length=20, verbose_name='店铺平台'),
            preserve_default=False,
        ),
    ]
