# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170320_1122'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shop',
            table='shops',
        ),
    ]
