# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-06 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20170615_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='pgoods_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='平台商品id'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopkeepername',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='掌柜名称'),
        ),
    ]
