# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQFriends',
            fields=[
                ('QQid', models.IntegerField(primary_key=True, serialize=False)),
                ('QQFriends', models.IntegerField(max_length=80)),
            ],
            options={
                'verbose_name': 'QQFriends',
                'verbose_name_plural': 'QQFriends',
            },
        ),
        migrations.CreateModel(
            name='QQFriendslog',
            fields=[
                ('QQid', models.IntegerField(primary_key=True, serialize=False)),
                ('QQfriends', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'add'), (2, 'delete')])),
            ],
            options={
                'verbose_name': 'QQFriendslog',
                'verbose_name_plural': 'QQFriendslog',
            },
        ),
        migrations.CreateModel(
            name='QQID',
            fields=[
                ('QQid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'QQID',
                'verbose_name_plural': 'QQID',
            },
        ),
    ]
