# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0002_qqfriends_qqfriendslog_qqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileid',
            name='QQ',
            field=models.IntegerField(null=True),
        ),
    ]
