# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0006_auto_20170901_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletask',
            name='UserPortkey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoweb.UserPortrait'),
        ),
        migrations.AlterField(
            model_name='mobiletask',
            name='mobileid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autoweb.mobileid'),
        ),
    ]
