# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0007_auto_20170901_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiletask',
            old_name='UserPortkey',
            new_name='UserPortraitId',
        ),
    ]
