# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0008_auto_20170901_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='QQGroup',
            fields=[
                ('QQ', models.IntegerField(primary_key=True, serialize=False)),
                ('QQGroup', models.IntegerField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'QQGroup',
                'verbose_name_plural': 'QQGroup',
            },
        ),
        migrations.CreateModel(
            name='QQGroupList',
            fields=[
                ('QQGroup', models.IntegerField(primary_key=True, serialize=False)),
                ('QQGroupList', models.IntegerField(null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'QQGroupList',
                'verbose_name_plural': 'QQGroupList',
            },
        ),
        migrations.CreateModel(
            name='QQGroupListlog',
            fields=[
                ('QQGroup', models.IntegerField(primary_key=True, serialize=False)),
                ('QQGroupList', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'add'), (2, 'delete')])),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'QQGroupList',
                'verbose_name_plural': 'QQGroupList',
            },
        ),
        migrations.CreateModel(
            name='QQGrouplog',
            fields=[
                ('QQ', models.IntegerField(primary_key=True, serialize=False)),
                ('QQGroup', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'add'), (2, 'delete')])),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'QQGrouplog',
                'verbose_name_plural': 'QQGrouplog',
            },
        ),
        migrations.RenameField(
            model_name='qqfriends',
            old_name='QQid',
            new_name='QQ',
        ),
        migrations.RenameField(
            model_name='qqfriends',
            old_name='QQfriends',
            new_name='QQFriends',
        ),
        migrations.RenameField(
            model_name='qqfriendslog',
            old_name='QQid',
            new_name='QQ',
        ),
        migrations.RenameField(
            model_name='qqfriendslog',
            old_name='QQfriends',
            new_name='QQFriends',
        ),
        migrations.RenameField(
            model_name='qqid',
            old_name='QQid',
            new_name='QQ',
        ),
        migrations.AddField(
            model_name='qqfriends',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='qqfriendslog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
