# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0009_auto_20170901_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqgroup',
            name='QQGroupName',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
