# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0012_auto_20170904_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqid',
            name='QQ',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
