# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-04 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0013_auto_20170904_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqfriends',
            name='QQ',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qqfriendslog',
            name='QQ',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qqgroup',
            name='QQ',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qqgrouplist',
            name='QQGroup',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qqgrouplistlog',
            name='QQGroup',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qqgrouplog',
            name='QQ',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qqid',
            name='QQ',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
