# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0016_qqfriends_qqfriendslog_qqgroup_qqgrouplist_qqgrouplistlog_qqgrouplog_qqid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileid',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
