# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0018_auto_20170907_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qqgrouplist',
            old_name='QQGroupList',
            new_name='QQ',
        ),
        migrations.RenameField(
            model_name='qqgrouplistlog',
            old_name='QQGroupList',
            new_name='QQ',
        ),
        migrations.AddField(
            model_name='qqgrouplistlog',
            name='contains',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='qqgrouplistlog',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qqgrouplistlog',
            name='status',
            field=models.IntegerField(choices=[(1, 'add'), (2, 'delete')], null=True),
        ),
    ]
