# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0019_auto_20170907_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqgrouplist',
            name='level',
            field=models.IntegerField(null=True),
        ),
    ]
