# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0020_qqgrouplist_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqgrouplist',
            name='QQ',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qqgrouplistlog',
            name='QQ',
            field=models.BigIntegerField(null=True),
        ),
    ]
