# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0021_auto_20170907_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qqgrouplist',
            name='QQ',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='qqgrouplistlog',
            name='QQ',
            field=models.IntegerField(null=True),
        ),
    ]
