# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0024_auto_20170907_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqfriends',
            name='contains',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qqfriends',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='qqfriends',
            name='nick',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='qqfriendslog',
            name='contains',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='qqfriendslog',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='qqfriendslog',
            name='nick',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
