# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0026_auto_20170908_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='qqid',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='qqid',
            name='password',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
