# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoweb', '0029_auto_20170912_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletask',
            name='SpecifyEndTime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobiletask',
            name='SpecifyStartTime',
            field=models.IntegerField(null=True),
        ),
    ]
