# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_mobileid_webserverurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobileAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QQ', models.CharField(max_length=100)),
                ('QQps', models.CharField(max_length=100)),
                ('wechat', models.CharField(max_length=100)),
                ('wechatps', models.CharField(max_length=100)),
                ('mobileid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.mobileid')),
            ],
        ),
    ]
