# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_mobileaccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobileaccount',
            options={'verbose_name': 'mobileAccount', 'verbose_name_plural': 'mobileAccount'},
        ),
        migrations.AlterField(
            model_name='mobileaccount',
            name='QQ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobileaccount',
            name='QQps',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobileaccount',
            name='wechat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobileaccount',
            name='wechatps',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
