# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_auto_20170718_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileaccount',
            name='QQmobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobileaccount',
            name='wechatmobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
