# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 11:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_auto_20170719_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiletasklog',
            options={'verbose_name': 'mobiletasklog', 'verbose_name_plural': 'mobiletasklog'},
        ),
        migrations.AddField(
            model_name='mobiletasklog',
            name='logdatetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 20, 11, 8, 25, 137580)),
        ),
        migrations.AddField(
            model_name='mobiletasklog',
            name='logid',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='mobiletasklog',
            name='logname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
