# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-19 20:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWoopGameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 10, 19, 20, 28, 54, 399186))),
                ('score', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='woopGameName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woopGameName', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='woopGameObstacles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObstaclesSort', models.CharField(choices=[(1, 'mood'), (2, 'perform'), (3, 'bug'), (4, 'Rules')], max_length=80, null=True)),
                ('Obstacles', models.CharField(max_length=300, null=True)),
                ('whenTime', models.CharField(max_length=200, null=True)),
                ('whenmethod', models.CharField(max_length=999, null=True)),
                ('score', models.IntegerField()),
                ('woopGameNameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woopgame.woopGameName')),
            ],
        ),
        migrations.CreateModel(
            name='woopGameOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValueObject', models.CharField(max_length=70, null=True)),
                ('Value', models.CharField(max_length=999, null=True)),
                ('woopGameNameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woopgame.woopGameName')),
            ],
        ),
        migrations.CreateModel(
            name='WoopGameReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woopGameReward', models.CharField(max_length=900, null=True)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 10, 19, 20, 28, 54, 400143))),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WoopGameScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('woopGameObstacles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woopgame.woopGameObstacles')),
            ],
        ),
    ]
