# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=20, verbose_name='买家账号')),
                ('buyerMobile', models.IntegerField(null=True, verbose_name='买家手机')),
                ('buyeraddress', models.CharField(max_length=11, null=True, verbose_name='地址')),
                ('blacklistsort', models.CharField(max_length=11, null=True, verbose_name='类别')),
                ('buyeralipay', models.CharField(max_length=11, null=True, verbose_name='支付宝账户')),
                ('proveimages1', models.CharField(max_length=20, null=True, verbose_name='证明图片')),
                ('shllerimages', models.CharField(max_length=20, null=True, verbose_name='卖家证明图片')),
                ('note', models.CharField(max_length=50, null=True, verbose_name='备注')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '黑名单',
            },
        ),
    ]
