# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryorder',
            name='platForm',
        ),
        migrations.AddField(
            model_name='cryorder',
            name='platform',
            field=models.CharField(choices=[('taobao', 'taobao'), ('jd', 'jd'), ('tmall', 'tmall'), ('1688', '1688')], max_length=20, null=True, verbose_name='店铺平台'),
        ),
    ]
