# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryapp', '0002_auto_20170609_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryorder',
            name='PlatformOrdersid',
            field=models.IntegerField(default=0, null=True, verbose_name='平台订单编号'),
        ),
    ]
