# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryapp', '0003_auto_20170519_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryorder',
            name='OrderSort',
            field=models.IntegerField(choices=[(1, '红包任务'), (2, '好评返现'), (3, '免费试用')], null=True, verbose_name='订单分类'),
        ),
    ]
