# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryapp', '0005_auto_20170519_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryorder',
            name='buyerid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='buyerId买家'),
            preserve_default=False,
        ),
    ]
