# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryapp', '0005_auto_20170619_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryorder',
            name='Money',
        ),
        migrations.AddField(
            model_name='cryorder',
            name='Express',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='快递费'),
        ),
        migrations.AddField(
            model_name='cryorder',
            name='buyerMoney',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='买手费用'),
        ),
        migrations.AddField(
            model_name='cryorder',
            name='sellerMoney',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='商家费用'),
        ),
        migrations.AddField(
            model_name='cryorder',
            name='交易金额',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
