# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryapp', '0006_auto_20170622_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryorder',
            old_name='交易金额',
            new_name='Money',
        ),
    ]
