# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryapp', '0006_cryorder_buyerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryorder',
            name='Status',
            field=models.IntegerField(choices=[(0, '关闭'), (1, '启动'), (2, '接任务'), (3, '提交等待审核'), (4, '审核通过'), (5, '完成')], verbose_name='状态启动与关闭'),
        ),
        migrations.AlterField(
            model_name='cryorder',
            name='buyerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='buyerId买家'),
        ),
    ]
