# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 09:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单id')),
                ('customer_id', models.IntegerField(null=True, verbose_name='会员')),
                ('shop_id', models.IntegerField(null=True, verbose_name='店铺')),
                ('good_id', models.IntegerField(null=True, verbose_name='商品')),
                ('keyword', models.CharField(max_length=50, null=True, verbose_name='关键词')),
                ('count', models.IntegerField(default=0, null=True, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, null=True, verbose_name='金额')),
                ('status', models.IntegerField(null=True, verbose_name='订单状态')),
                ('error_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('platform', models.CharField(choices=[('taobao', '淘宝'), ('jd', '京东')], max_length=20, null=True, verbose_name='平台')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='商家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
            },
        ),
    ]
