# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 17:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jdorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbOrderKeyword', models.CharField(max_length=50, verbose_name='淘宝关键词')),
                ('tbOrderNumber', models.IntegerField(verbose_name='数量')),
                ('Amount', models.FloatField(verbose_name='金额')),
                ('jdOrderState', models.IntegerField(verbose_name='订单状态1.审核2,完成.3,失败,4执行中,5失败,6.审核未通过')),
                ('jdOrderError', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('JDGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.JDGoods', verbose_name='jd产品ID')),
                ('jdshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.jdshop', verbose_name='京东店铺')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '京东订单',
                'verbose_name_plural': '京东订单',
            },
        ),
        migrations.CreateModel(
            name='tborder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tbOrderKeyword', models.CharField(max_length=50, verbose_name='淘宝关键词')),
                ('tbOrderNumber', models.IntegerField(verbose_name='数量')),
                ('Amount', models.FloatField(max_length=50, verbose_name='金额')),
                ('tbOrderState', models.IntegerField(verbose_name='订单状态1.审核2,完成.3,失败,4执行中,5失败,6.审核未通过')),
                ('tbOrderError', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('TaobaoGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.TaobaoGoods', verbose_name='tb产品ID')),
                ('taobaoshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.taobaoshop', verbose_name='淘宝店铺')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '淘宝订单',
                'verbose_name_plural': '淘宝订单',
            },
        ),
    ]
